<!-- Formulaire de saisie d'un nouvel article -->
<?php if ($errorMessage != ''):?>
    <div class="alert alert-danger"><?=$errorMessage?></div>
<?php endif; ?>
<form action="<?= $requestUrl ?>/admin/categories/edit/" method="post" enctype="multipart/form-data">

        <div class="form-group row">
            <label for="name">Nom :</label></br>
            <input class="form-control" type="text" id="name" name="name" value="<?=$name?>">
        </div>
        
        <div class="form-group row">
            <label class="textarea" for="contents">Description :</label></br>
            <textarea class="form-control" id="contents" name="contents" rows="15"><?=$contents?></textarea>
        </div>

        <div class="form-group row">
            <label for="picture">Image :</label></br>	
            <input class="form-control-file" type="file" name="picture" id="picture" accept="image/png,image/jpeg,image/gif">
            <?php if(!is_null($originalpicture)):?>
                <img src="<?= $wwwUrl ?>/uploads/categories/<?=$originalpicture?>"/>
            <?php else:?>
                <img src="https://via.placeholder.com/100" />
            <?php endif;?>
        </div>

        <div class="text-center">
            <a href="<?= $requestUrl ?>/admin/categories/" class="btn btn-outline-dark" role="button">Annuler</a>
            <input type="submit" value="Enregistrer" class="btn btn-outline-success" >
        </div>

        <input type="hidden" name="originalpicture" value="<?=$originalpicture?>">
        <input type="hidden" name="id" value="<?=$id?>">
</form>