<!-- Issue #1 Formulaire de saisie d'un nouvel article -->
<h2><?=$product['prod_name']?> <span class="badge badge-primary"><?=$product['prod_price']?> € HT</span></h2>
<?php if ($errorMessage != ''):?>
    <div class="alert alert-danger"><?=$errorMessage?></div>
<?php endif; ?>

<form action="<?= $requestUrl ?>/admin/products/variations/add/" method="post" enctype="multipart/form-data">

        <div class="form-group row">
            <label for="name">Nom :</label>
            <input class="form-control" type="text" id="name" name="name" value="<?=$name?>">
        </div>
        <div class="form-group row">
            <label for="price">Variation de prix :</label>
            <div class="input-group">
                <input type="text" class="form-control" aria-label="Price" id="price" name="price" value="<?=$price?>">
                <div class="input-group-append">
                    <span class="input-group-text">€ HT</span>
                </div>
            </div>
             <small id="passwordHelp" class="form-text text-muted">Fixez ici la variation HT du prix par rapport au produit. Valeur négative pour un prix en baisse.</small>
        </div>
        <div class="form-group row">
            <label for="quantity">Quantité en stock :</label>
            <input class="form-control" type="text" id="quantity" name="quantity" value="<?=$quantity?>">
        </div>
        <div class="text-center">
            <a href="<?= $requestUrl ?>/admin/products/variations/?productid=<?=$productid?>" class="btn btn-outline-dark" role="button">Annuler</a>
            <input type="submit" value="Enregistrer" class="btn btn-outline-success" >
        </div>

        <input type="hidden" name="productid" value="<?=$productid?>">
</form>