<section class="table-responsive">
<p>
<a class="btn btn-dark" role="button" href="<?= $requestUrl ?>/admin/products/?id=<?=$product['prod_id']?>"><i class="fas fa-arrow-left"></i> Retour</a>
<a class="btn btn-primary" role="button" href="<?= $requestUrl ?>/admin/products/variations/add/?productid=<?=$product['prod_id']?>"><i class="fas fa-plus-square"></i> Ajouter une variation</a>
</p>
<h2><?=$product['prod_name']?> <span class="badge badge-primary"><?=$product['prod_price']?> € HT</span></h2>
    <table class="tableDonnee table">
        <thead>
            <th>Id</th>
            <th>Nom</th>
            <th class="text-right">Variation du prix € HT</th>
            <th class="text-right">Quantité en stock</th>
            <th></th>
        </thead>
        <tbody>
            <?php foreach($variations as $variation):?>
                <tr>
                    <td><?=$variation['prodv_id']?></td>
                    <td><?=$variation['prodv_name']?></td>
                    <td class="text-right"><?php if ($variation['prodv_price'] >= 0){ echo '+';}?><?=$variation['prodv_price']?> € HT <span class="badge badge-primary"><?=$variation['prodv_price'] + $product['prod_price']?> € HT </span></td>
                    <td class="text-right"><?=$variation['prodv_quantity']?></td>
                    <td><a href="<?= $requestUrl ?>/admin/products/variations/edit/?productid=<?=$variation['product_prod_id']?>&id=<?=$variation['prodv_id']?>"><i class="fas fa-edit"></i></a> <a href="<?= $requestUrl ?>/admin/products/variations/del/?productid=<?=$variation['product_prod_id']?>&id=<?=$variation['prodv_id']?>"  data-toggle="modal" data-target="#delete"><i class="fas fa-trash-alt"></i></a></td>
                </tr>
            <?php endforeach;?>
        </tbody>
    </table>
</section>