<main class="container">
    <section class="cartDisplay">
        <h1>Votre panier</h1>
         <?php 
          if(isset($flashbag) && $flashbag!=false):
            foreach($flashbag as $message):?>
              <div class="alert alert-success"><?=$message?></div>
          <?php 
            endforeach;
          endif;
        ?>
        <table id="cartTable">
            <thead>
                <tr>
                    <th></th>
                    <th>Produit(s)</th>
                    <th>Quantité</th>
                    <th>Prix unitaire</th>
                    <th>Prix total</th>
                    <th></th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th colspan="4">Total de votre panier</th>
                    <th colspan="2" class='total'>0 €</th>
                </tr>
            </tfoot>
            <tbody>
            </tbody>
        </table>
         <a href="<?=$requestUrl?>/product/liste" class="btn"><i class="fas fa-cart-arrow-down"></i> Continuez mes achats</a>
        <?php if ($userSession->isAuthenticated()):?>
            <form id="formCart" action="<?=$requestUrl?>/order/" method="POST">
                <input type="hidden" value="" id="cartInput" name="cartInput">
                <input type="submit" id="cartSubmit" class="btn" value="Voir la commande et payer !">
            </form>
        <?php else:?>
            <a href="<?=$requestUrl?>/customer" class="btn" id="cartSubmit"><i class="fas fa-sign-in-alt"></i> Connectez vous pour commander</a>
        <?php endif;?>
    </section>
</main>

<!--Modal de confirmation-->
 <div id="confirm">
    <div><a href="#" class="close"><i class="fas fa-times fa-3x"></i></a></div>
    <h2>Voulez vous supprimer cet élément ?</h2>
    <p><a href="#" class="button close"><i class="fas fa-times"></i> Non</a><a href="#" class="button valid"><i class="fas fa-check"></i> Oui</a></p>
</div>